# Generated by Django 5.1 on 2024-08-28 05:42

import django.db.models.deletion
import phone_field.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnquiryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry_id', models.CharField(max_length=64, null=True)),
                ('customer_name', models.CharField(max_length=64, null=True)),
                ('your_email', models.EmailField(max_length=128, null=True)),
                ('phone_number', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('org_details', models.CharField(max_length=64, null=True)),
                ('your_requirement', models.CharField(max_length=64, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalesQuoteDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=264, null=True)),
                ('product_id', models.CharField(max_length=128, null=True)),
                ('product_details', models.CharField(max_length=128, null=True)),
                ('time_period', models.CharField(choices=[('3 Months', '3 Months'), ('6 Months', '6 Months'), ('9 Months', '9 Months'), ('1 Year', '1 Year')], default='Other', max_length=200, null=True)),
                ('pricing', models.CharField(max_length=64, null=True)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.enquirydetails')),
            ],
        ),
        migrations.CreateModel(
            name='CompleteDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.enquirydetails')),
                ('salesquote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.salesquotedetails')),
            ],
        ),
    ]
