# Generated by Django 5.1 on 2024-08-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_salesquotedetails_added_to_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdetails',
            name='total_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cartdetails',
            name='qty',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='salesquotedetails',
            name='qty',
            field=models.IntegerField(null=True),
        ),
    ]
