# Generated by Django 5.1 on 2024-08-31 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.cartdetails'),
        ),
    ]
