# Generated by Django 5.1 on 2024-09-05 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_products_salesquotedetails_product_obj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdetails',
            name='enquiry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.enquirydetails'),
        ),
        migrations.AlterField(
            model_name='cartdetails',
            name='qty',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='cartdetails',
            name='sq_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.salesquotedetails'),
        ),
        migrations.AlterField(
            model_name='cartdetails',
            name='time_period',
            field=models.CharField(choices=[('3 Months', '3 Months'), ('6 Months', '6 Months'), ('9 Months', '9 Months'), ('1 Year', '1 Year')], default='1 Year', max_length=200, null=True),
        ),
    ]
