# Generated by Django 5.1 on 2024-09-05 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0009_alter_cartdetails_enquiry_alter_cartdetails_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdetails',
            name='product_obj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.products'),
        ),
    ]
