# Generated by Django 5.1 on 2024-09-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0010_cartdetails_product_obj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdetails',
            name='total_amount',
            field=models.IntegerField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='myorder',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
    ]
